<a href="https://colab.research.google.com/github/3m6d/ML-techniques-practise/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
import pandas as pd

file_path = '/content/drive/My Drive/Colab Notebooks/student_performance.csv'

df = pd.read_csv(file_path)

In [ ]:
print(df.head())

   Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0  


In [ ]:
df.shape

(10000, 6)

In [ ]:
df["Extracurricular Activities"] = df["Extracurricular Activities"].map({'Yes': 1, 'No' : 0})

In [ ]:
# since we are predicting performance index
y = df["Performance Index"]

In [ ]:
x = df.drop("Performance Index", axis = 1)

Training Linear Regression model

Y = mx + c
m = coefficient
c = intercept

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

# x
# y
# test size means in this sample of 10k, i have  chosen 0.2 which means 20% of the dataset

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

In [ ]:
reg.intercept_

-33.92194621555638

In [ ]:
reg.coef_

array([2.85248393, 1.0169882 , 0.60861668, 0.47694148, 0.19183144])

The number of coefficient = 5 i.e. number of X
 y = mx1 + mx2 + mx3 + mx4 ...... + c

In [ ]:
import numpy as np
np.array(x_train)[13]

array([ 6, 82,  0,  5,  8])

Testing

In [ ]:
pred = reg.predict(x_test)

In [ ]:
np.array(x_test)[3]

array([ 6, 42,  1,  8,  5])

In [ ]:
np.array(y_test)[3]

28.0

In [ ]:
pred[3]

31.289767480301528

Evaluation Metrics

MSE
RMSE
MAE
R2
ADj R2

GridSearch

Ridge

Lasso

The r2_score function in sklearn.metrics calculates the R-squared (coefficient of determination) value, which measures how well the model's predictions approximate the actual target values. However, it doesn't inherently "ignore" unimportant features; it evaluates the predictions based on the input features and the actual target values.

In [ ]:
from sklearn.metrics import r2_score

r2_score(pred, y_test)

##doesnt consider not important features,
## features sufficient cha ki chaian

0.9887203279837657

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error


In [ ]:
mse = mean_squared_error(pred, y_test)
mse

4.0826283985218526

In [ ]:
mae = mean_absolute_error(pred, y_test)
mae

1.6111213463123042

In [ ]:
rmse = np.sqrt(mean_squared_error(y_test, pred))
print(f"RMSE: {rmse}")


RMSE: 2.0205515085050054



LASSO Regression

In [ ]:
from sklearn.linear_model import Lasso, Ridge

ridge = Ridge()
lasso = Lasso()

In [ ]:
parameter={'alpha':[1,2,4,6,6.5,6.8,7,8,10, 12, 15, 18, 20, 63.83,1.5,2]}
parameter

{'alpha': [1, 2, 4, 6, 6.5, 6.8, 7, 8, 10, 12, 15, 18, 20, 63.83, 1.5, 2]}

In [ ]:
from sklearn.model_selection import GridSearchCV

ridgegrid = GridSearchCV(ridge, param_grid=parameter, scoring='neg_mean_squared_error', cv=5)
ridgegrid.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1, 2, 4, 6, 6.5, 6.8, 7, 8, 10, 12, 15, 18,
                                   20, 63.83, 1.5, 2]},
             scoring='neg_mean_squared_error')